### ISSUE TITLE
panic报错

### ISSUE THREAD

**Issue by pandak1d** [chaitin/rad#81]
在爬取过程中报错

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0xcf340e]

goroutine 33729 [running]:
github.com/go-rod/rod.(*Browser).RemoveState(...)
        /go/pkg/mod/github.com/go-rod/rod@v0.112.0/states.go:56
gunkit/ext/crawler/browser.(*ProTester).DoneTask.func1()
        /builds/lohengrin/gunkit/ext/crawler/browser/eventhandler.go:375 +0x1ce
sync.(*Once).doSlow(0xc015270a90, 0xc011741ef0)
        /usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
gunkit/ext/crawler/browser.(*ProTester).DoneTask(0xc00000a3c0, 0xc015270a50, 0xc0140d7fa0, 0x20)
        /builds/lohengrin/gunkit/ext/crawler/browser/eventhandler.go:369 +0x95
gunkit/ext/crawler/browser.(*ProTester).updateTargetInfo.func1(0xc00000a3c0, 0x1334518, 0xc014b80f00, 0xc015270a50)
        /builds/lohengrin/gunkit/ext/crawler/browser/targetContext.go:41 +0x145
created by gunkit/ext/crawler/browser.(*ProTester).updateTargetInfo
        /builds/lohengrin/gunkit/ext/crawler/browser/targetContext.go:33 +0x1d1

**Comment by Zheisbug** [comment]
+1
